### PR TITLE
Support ES2015 template strings

### PR DESCRIPTION
**Pull request by bradbarrow**
Why:

* ES2015 allows backticks to enclose template strings
* Many projects are written in ES2015 and it's more common for developers to use backticks by default for strings

This change addresses the need by:

* Introcucing a regex that allows backticks

### CODE REVIEW

**Comment by tboerger** [comment]
Thanks!

**Comment by tboerger** [comment]
Will release a new gem version in a few minutes.

**Comment by bradbarrow** [comment]
Thanks for being responsive @tboerger

**Comment by tboerger** [comment]
That's why I took the maintainance :)

**Pull request merged**
